### ISSUE TITLE
Partial out sun

### ISSUE THREAD

**Issue by dirkonet** [fsr/stats#1]
Especially Saturday looks a lot like the position of the sun. Would it be possible to partial out the solar noise of several "office closed" days? Another method would be to only count values above the threshold or use binary open/closed values to generate the punchcard.

**Comment by kiliankoe** [comment]
Using binary values based on the threshold seems like the most sensible option. They represent the data we want to use for things like this.

**Comment by Feliix42** [comment]
Remember, that there were several Hackathons which caused some light, too. But yes, seems like there is some sun influence.

I'm against strict binary values, because I intended to have differing values to indicate, that the probability of catching someone in the office is not always the same (e.g. 11:00 - 12:00) and to underline that we simply don't have strict office hours.

During the filtering process I could simply discard values below 300, how about that?

**Comment by dirkonet** [comment]
Binary processing of the original data, not binary representation of the output. Which is kind of the same as using the threshold (currently 500 to protect shy people hiding in the semi-darkness).

**Comment by kiliankoe** [comment]
Discarding values below the threshold is exactly what we meant. Setting those to mean closed and all others as open is the binary representation we meant 😊

**Comment by kiliankoe** [comment]
Argh, can't edit stupidly worded comment from mobile 😞

**Comment by Feliix42** [comment]
Sorry, my fault :smile:

For the statistics I would set the threshold to 300 to include the dizzy semi-darkness because technically, someone _was_ there.

**Comment by Feliix42** [comment]
So this is, what it looked like previously:
![previous](https://raw.githubusercontent.com/fsr/stats/master/assets/example.png)

And this is how it looks like now, after I set every value below 300 to 0:
![after](https://cloud.githubusercontent.com/assets/9332912/14330372/9c891154-fc40-11e5-8a3a-37b307e98409.png)

I checked the output of the last days, which were relatively sunny: 300 seems to be a good value to distinguish between activity from the sun and the artificial office light.
